name = input("Product Name : ")
quantity = int(input("No of quantity : "))
price = float(input("Price of each product : "))
print("*" * 25, "BILL", "*" * 25)
print("Item Name     Item Quality     Item Price")
print(f"{name}            {quantity}            {price}")
print("*" * 50)
print(f"Total Amount to be paid:       {quantity * price}")
print("*" * 50)
